require 'sinatra'
require './lib/task/db'

namespace :db do
  task :environment do
    require 'sequel'
    ENV['DATABASE_URL']  ||=
      'postgres://postgres:1234@localhost/sinatra_seq'
    ENV['RACK_ENV'] ||= 'development'
    ENV['DATABASE'] = 'api_hh_development' if ENV['RACK_ENV'] == 'development'
    ENV['DATABASE'] = 'api_hh_test' if ENV['RACK_ENV'] == 'test'
    ENV['DATABASE'] = 'api_hh_production' if ENV['RACK_ENV'] == 'production'
  end
end
